### ISSUE TITLE
Migrate to K8S and define a Helm chart

### ISSUE THREAD

**Issue by JasonFreeberg** [crunch-time/crunchtime#29]
### Background

Today, the application runs as a Docker container, but the database and cache must be hosted separately. This means if a university wants to use CrunchTime, they need to host the container, create a DB, create a cache and wire them together.    That's a lot of moving parts and a pretty big learning curve to host what's a pretty simple application.

### Problem

- As a university developer or IT professional, deploying and connecting all these components is too difficult.

### Working Solution

If we define a Kubernetes configuration file for the application, database, cache (and any future components) this would decrease the number of unique services a university developer would need to deploy. Furthermore, we could then define a Helm chart for the application to distribute it more easily for universities. From there, it *should* be much easier for an IT professional to "just run" the application on a Kubernetes cluster (likely a managed service through a cloud provider).

### Open questions

- If the application is distributed via Helm, how does a user apply/manage updates (v1.2 -> v1.3)?
- Containers are inherently ephemeral so if the database is run as a container, how is data persisted?
  - [Storage volume example](https://severalnines.com/database-blog/using-kubernetes-deploy-postgresql)

**Comment by adhil0** [comment]
> If the application is distributed via Helm, how does a user apply/manage updates (v1.2 -> v1.3)?

From what I understand, the user would run a `helm upgrade` command with the new version number. For example, if you were managing a JupyterHub cluster, you could upgrade the version to 0.10.6 by running 
`helm upgrade --cleanup-on-fail \
  --install $RELEASE jupyterhub/jupyterhub \
  --namespace $NAMESPACE \
  --create-namespace \
  --version=0.10.6 \
  --values config.yaml`.  

I got this example from the [Zero to JupyterHub with Kubernetes](https://zero-to-jupyterhub.readthedocs.io/en/stable/) documentation, which was useful for me to play around with Kubernetes and Helm from a user's perspective.
